baseURL = "http://leslieemeryphd.com/"
languageCode = "en-us"
title = "Leslie Emery, PhD"
theme = "whiteplain"

[taxonomies]
    tag = "tags"
    

[permalinks]
    post = "/:filename/"

[params]
    useCND = true
    dateFormat = "January 2, 2006"
    showShareIcons = false

    # For the About page.
    [params.author]
      name = "Leslie S. Emery"
      linkedin = "leslie-emery"
      github = "leslem"
      email = "leslie.s.emery@gmail.com"
      avatar = "/static/images/profile.jpg"

    [[menu.main]]
        name = "Posts"
        identifier = "posts"
        url = "/post/"
        weight = 1
    [[menu.main]]
        name = "CV"
        url = "/cv/"
        weight = 2
    [[menu.main]]
      name = "Categories"
      identifier = "categories"
      url = "/categories/"
      weight = 3
    [[menu.main]]
      name = "Tags"
      identifier = "tags"
      url = "/tags/"
      weight = 4
    [[menu.main]]
      name = "Archives"
      identifier = "archives"
      url = "/archives/"
      weight = 5
    [[menu.main]]
      name = "About"
      identifier = "about"
      url = "/"
      weight = 6

