baseURL = "http://leslieemeryphd.com/"
languageCode = "en-us"
title = "Leslie Emery, PhD"

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/:filename/"

[params]
    description = "Leslie S. Emery"
    contentBackgroundColor = "#FFFFFF"
    contentTextColor = "#2B2B2B"
    contentLinkColor = "#8f8f8f"
    contentLinkHoverColor = "#2B2B2B"
    navbarBackgroundColor = "#FFFFFF"
    navbarLinkColor = "#2B2B2B"
    navbarLinkHoverColor = "#FFFFFF"
    wrapperMaxWidth = "800px"
    customDateFormat = "Jan 2, 2006"
    customCodeStyle = true
    customBlockquoteStyle = true
    showPostSummary = false
    googleAnalytics = "UA-123456789-1"
    cookieConsent = true
    includeBootstrapJs = true
    faviconSafariPinnedTabColor = "#5bbad5"
    faviconMsApplicationTileColor = "#da532c"
    faviconThemeColor = "#ffffff"
    header2to5color = "#666666"
    mainSections = ['post', ]

[menu]
    # [[menu.nav]]
    # name = "Home"
    # url = "/"
    # weight = 1
    [[menu.nav]]
    name = "Posts"
    url = "/post/"
    weight = 2
    [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
    [[menu.nav]]
    name = "CV"
    url = "/page/cv/"
    weight = 4
    # [[menu.nav]]
    # name = "RSS"
    # url = "/index.xml"
    # weight = 4
